using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;
using System.Threading.Tasks;
using Windows.Storage;
using System.Collections;

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=234238

namespace Culinars
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class HomePage : Page
    {
        int CurrentSearch;




        public HomePage()
        {

            this.InitializeComponent();
            populate();
            

        }

        private void populate()
        {
            listBox.Items.Clear();

            listBox.Items.Add("Acidulated water");
            listBox.Items.Add("Ackee");
            listBox.Items.Add("Acorn squash");
            listBox.Items.Add("Aduki beans");
            listBox.Items.Add("Agar-agar");
            listBox.Items.Add("Ale");
            listBox.Items.Add("Alfalfa sprouts");
            listBox.Items.Add("Allspice");
            listBox.Items.Add("Almond");
            listBox.Items.Add("Almond essence");
            listBox.Items.Add("Almond extract");
            listBox.Items.Add("Amaranth");
            listBox.Items.Add("Amaretti");
            listBox.Items.Add("Anchovies");
            listBox.Items.Add("Anchovy essence");
            listBox.Items.Add("Angelica");
            listBox.Items.Add("Angostura bitters");
            listBox.Items.Add("Anise");
            listBox.Items.Add("Apple");
            listBox.Items.Add("Apple chutney");
            listBox.Items.Add("Apple juice");
            listBox.Items.Add("Apple sauce");
            listBox.Items.Add("Apricot");
            listBox.Items.Add("Apricot jam");
            listBox.Items.Add("Arborio rice");
            listBox.Items.Add("Arbroath smokie");
            listBox.Items.Add("Argan oil");
            listBox.Items.Add("Arrowroot");
            listBox.Items.Add("Artichoke");
            listBox.Items.Add("Asafoetida");
            listBox.Items.Add("Asparagus");
            listBox.Items.Add("Aubergine");
            listBox.Items.Add("Avocado");
            listBox.Items.Add("Bacon");
            listBox.Items.Add("Bagel");
            listBox.Items.Add("Baguette");
            listBox.Items.Add("Baked beans");
            listBox.Items.Add("Baking");
            listBox.Items.Add("Baking powder");
            listBox.Items.Add("Balsamic vinegar");
            listBox.Items.Add("Bamboo shoots");
            listBox.Items.Add("Banana");
            listBox.Items.Add("Banana bread");
            listBox.Items.Add("Barbary duck");
            listBox.Items.Add("Barbecue sauce");
            listBox.Items.Add("Barley");
            listBox.Items.Add("Basil");
            listBox.Items.Add("Basmati rice");
            listBox.Items.Add("Bay boletes");
            listBox.Items.Add("Bay leaf");
            listBox.Items.Add("Beans");
            listBox.Items.Add("Beansprouts");
            listBox.Items.Add("Bechamel sauce");
            listBox.Items.Add("Beef");
            listBox.Items.Add("Beef consomme");
            listBox.Items.Add("Beef dripping");
            listBox.Items.Add("Beef mince");
            listBox.Items.Add("Beef ribs");
            listBox.Items.Add("Beef rump");
            listBox.Items.Add("Beef sausage");
            listBox.Items.Add("Beef stock");
            listBox.Items.Add("Beef tomato");
            listBox.Items.Add("Beer");
            listBox.Items.Add("Beetroot");
            listBox.Items.Add("Berry");
            listBox.Items.Add("Best end");
            listBox.Items.Add("Betel leaves");
            listBox.Items.Add("Beurre manie");
            listBox.Items.Add("Bicarbonate of soda");
            listBox.Items.Add("Bilberries");
            listBox.Items.Add("Bird's-eye chillies");
            listBox.Items.Add("Biscotti");
            listBox.Items.Add("Biscuits");
            listBox.Items.Add("Blachan");
            listBox.Items.Add("Black beans");
            listBox.Items.Add("Black bream");
            listBox.Items.Add("Black eyed beans");
            listBox.Items.Add("Black pepper");
            listBox.Items.Add("Black pudding");
            listBox.Items.Add("Black sesame seeds");
            listBox.Items.Add("Black treacle");
            listBox.Items.Add("Blackbean sauce");
            listBox.Items.Add("Blackberry");
            listBox.Items.Add("Blackcurrant");
            listBox.Items.Add("Blackcurrant juice drink");
            listBox.Items.Add("Blini");
            listBox.Items.Add("Blood orange");
            listBox.Items.Add("Blueberry");
            listBox.Items.Add("Boar");
            listBox.Items.Add("Bok choi");
            listBox.Items.Add("Bonito");
            listBox.Items.Add("Borage");
            listBox.Items.Add("Borlotti beans");
            listBox.Items.Add("Bouquet garni");
            listBox.Items.Add("Braising steak");
            listBox.Items.Add("Bramley apple");
            listBox.Items.Add("Bran");
            listBox.Items.Add("Brandy");
            listBox.Items.Add("Brandy butter");
            listBox.Items.Add("Brandy snaps");
            listBox.Items.Add("Bratwurst");
            listBox.Items.Add("Brazil nut");
            listBox.Items.Add("Bread");
            listBox.Items.Add("Bread roll");
            listBox.Items.Add("Bread sauce");
            listBox.Items.Add("Breadcrumbs");
            listBox.Items.Add("Breadfruit");
            listBox.Items.Add("Breadsticks");
            listBox.Items.Add("Bresaola");
            listBox.Items.Add("Brie");
            listBox.Items.Add("Brill");
            listBox.Items.Add("Brioche");
            listBox.Items.Add("Brisket");
            listBox.Items.Add("Broad beans");
            listBox.Items.Add("Broccoli");
            listBox.Items.Add("Broth");
            listBox.Items.Add("Brown bread");
            listBox.Items.Add("Brown lentil");
            listBox.Items.Add("Brown rice");
            listBox.Items.Add("Brown sauce");
            listBox.Items.Add("Brown shrimp");
            listBox.Items.Add("Brown sugar");
            listBox.Items.Add("Brussels sprouts");
            listBox.Items.Add("Buckwheat");
            listBox.Items.Add("Buckwheat flour");
            listBox.Items.Add("Bulgur wheat");
            listBox.Items.Add("Buns");
            listBox.Items.Add("Burger");
            listBox.Items.Add("Butter");
            listBox.Items.Add("Butter beans");
            listBox.Items.Add("Buttercream icing");
            listBox.Items.Add("Butterhead lettuce");
            listBox.Items.Add("Buttermilk");
            listBox.Items.Add("Butternut squash");
            listBox.Items.Add("Cabbage");
            listBox.Items.Add("Caerphilly");
            listBox.Items.Add("Cake");
            listBox.Items.Add("Calasparra rice");
            listBox.Items.Add("Calvados");
            listBox.Items.Add("Camembert");
            listBox.Items.Add("Campagne loaf");
            listBox.Items.Add("Candied peel");
            listBox.Items.Add("Cannellini beans");
            listBox.Items.Add("Cape gooseberries");
            listBox.Items.Add("Capers");
            listBox.Items.Add("Capsicum");
            listBox.Items.Add("Caramel");
            listBox.Items.Add("Caraway seeds");
            listBox.Items.Add("Cardamom");
            listBox.Items.Add("Carob");
            listBox.Items.Add("Carrageen moss");
            listBox.Items.Add("Carrot");
            listBox.Items.Add("Cashew");
            listBox.Items.Add("Cassava");
            listBox.Items.Add("Caster sugar");
            listBox.Items.Add("Catfish");
            listBox.Items.Add("Caul fat");
            listBox.Items.Add("Cauliflower");
            listBox.Items.Add("Cava");
            listBox.Items.Add("Caviar");
            listBox.Items.Add("Cavolo nero");
            listBox.Items.Add("Cayenne pepper");
            listBox.Items.Add("Celeriac");
            listBox.Items.Add("Celery");
            listBox.Items.Add("Celery seeds");
            listBox.Items.Add("Champ");
            listBox.Items.Add("Champagne");
            listBox.Items.Add("Chanterelle mushrooms");
            listBox.Items.Add("Chantilly cream");
            listBox.Items.Add("Chapati flour");
            listBox.Items.Add("Chapatis");
            listBox.Items.Add("Charcuterie");
            listBox.Items.Add("Chard");
            listBox.Items.Add("Charlotte potato");
            listBox.Items.Add("Chayote");
            listBox.Items.Add("Cheddar");
            listBox.Items.Add("Cheese");
            listBox.Items.Add("Cheese sauce");
            listBox.Items.Add("Cherry");
            listBox.Items.Add("Cherry brandy");
            listBox.Items.Add("Cherry tomatoes");
            listBox.Items.Add("Chervil");
            listBox.Items.Add("Cheshire");
            listBox.Items.Add("Chestnut");
            listBox.Items.Add("Chestnut mushrooms");
            listBox.Items.Add("Chicken");
            listBox.Items.Add("Chicken breast");
            listBox.Items.Add("Chicken leg");
            listBox.Items.Add("Chicken liver");
            listBox.Items.Add("Chicken soup");
            listBox.Items.Add("Chicken stock");
            listBox.Items.Add("Chicken thigh");
            listBox.Items.Add("Chicken wing");
            listBox.Items.Add("Chickpea");
            listBox.Items.Add("Chickpea flour");
            listBox.Items.Add("Chicory");
            listBox.Items.Add("Chilli");
            listBox.Items.Add("Chilli oil");
            listBox.Items.Add("Chilli paste");
            listBox.Items.Add("Chilli powder");
            listBox.Items.Add("Chilli sauce");
            listBox.Items.Add("Chinese cabbage");
            listBox.Items.Add("Chinese mushrooms");
            listBox.Items.Add("Chinese pancake");
            listBox.Items.Add("Chipotle");
            listBox.Items.Add("Chips");
            listBox.Items.Add("Chives");
            listBox.Items.Add("Chocolate");
            listBox.Items.Add("Chocolate biscuit");
            listBox.Items.Add("Chocolate brownies");
            listBox.Items.Add("Chocolate cake");
            listBox.Items.Add("Chocolate mousse");
            listBox.Items.Add("Chocolate truffle");
            listBox.Items.Add("Chopped tomatoes");
            listBox.Items.Add("Chorizo");
            listBox.Items.Add("Choux pastry");
            listBox.Items.Add("Christmas cake");
            listBox.Items.Add("Christmas pudding");
            listBox.Items.Add("Chuck and blade");
            listBox.Items.Add("Chump");
            listBox.Items.Add("Chutney");
            listBox.Items.Add("Ciabatta");
            listBox.Items.Add("Cider");
            listBox.Items.Add("Cinnamon");
            listBox.Items.Add("Citrus fruit");
            listBox.Items.Add("Clams");
            listBox.Items.Add("Clarified butter");
            listBox.Items.Add("Clementine");
            listBox.Items.Add("Clotted cream");
            listBox.Items.Add("Cloves");
            listBox.Items.Add("Cobnut");
            listBox.Items.Add("Cockles");
            listBox.Items.Add("Cocktail");
            listBox.Items.Add("Cocoa butter");
            listBox.Items.Add("Cocoa powder");
            listBox.Items.Add("Coconut");
            listBox.Items.Add("Coconut cream");
            listBox.Items.Add("Coconut milk");
            listBox.Items.Add("Coconut oil");
            listBox.Items.Add("Cod");
            listBox.Items.Add("Cod roe");
            listBox.Items.Add("Coffee");
            listBox.Items.Add("Coffee beans");
            listBox.Items.Add("Coffee essence");
            listBox.Items.Add("Coffee granules");
            listBox.Items.Add("Coffee liqueur");
            listBox.Items.Add("Cognac");
            listBox.Items.Add("Cola");
            listBox.Items.Add("Coleslaw");
            listBox.Items.Add("Coley");
            listBox.Items.Add("Collar");
            listBox.Items.Add("Compôte");
            listBox.Items.Add("Comte");
            listBox.Items.Add("Condensed milk");
            listBox.Items.Add("Confectionery");
            listBox.Items.Add("Coriander");
            listBox.Items.Add("Coriander cress");
            listBox.Items.Add("Coriander seeds");
            listBox.Items.Add("Corn oil");
            listBox.Items.Add("Corn syrup");
            listBox.Items.Add("Corned beef");
            listBox.Items.Add("Cornflour");
            listBox.Items.Add("Cos lettuce");
            listBox.Items.Add("Cottage cheese");
            listBox.Items.Add("Coulis");
            listBox.Items.Add("Courgette");
            listBox.Items.Add("Court bouillon");
            listBox.Items.Add("Couscous");
            listBox.Items.Add("Couverture");
            listBox.Items.Add("Crab");
            listBox.Items.Add("Crab apple");
            listBox.Items.Add("Crackers");
            listBox.Items.Add("Cranberry");
            listBox.Items.Add("Cranberry juice");
            listBox.Items.Add("Cranberry sauce");
            listBox.Items.Add("Crayfish");
            listBox.Items.Add("Cream");
            listBox.Items.Add("Cream cheese");
            listBox.Items.Add("Cream liqueur");
            listBox.Items.Add("Cream of tartar");
            listBox.Items.Add("Cream soda");
            listBox.Items.Add("Creamed coconut");
            listBox.Items.Add("Crème fraîche");
            listBox.Items.Add("Crêpe");
            listBox.Items.Add("Cress");
            listBox.Items.Add("Crispbread");
            listBox.Items.Add("Crisps");
            listBox.Items.Add("Croissant");
            listBox.Items.Add("Croûtons");
            listBox.Items.Add("Crudites");
            listBox.Items.Add("Crumble");
            listBox.Items.Add("Crystallised ginger");
            listBox.Items.Add("Cucumber");
            listBox.Items.Add("Cumberland sauce");
            listBox.Items.Add("Cumin");
            listBox.Items.Add("Curacao");
            listBox.Items.Add("Curd");
            listBox.Items.Add("Curd cheese");
            listBox.Items.Add("Curly kale");
            listBox.Items.Add("Currant bread");
            listBox.Items.Add("Currants");
            listBox.Items.Add("Curry");
            listBox.Items.Add("Curry leaves");
            listBox.Items.Add("Curry paste");
            listBox.Items.Add("Curry powder");
            listBox.Items.Add("Custard");
            listBox.Items.Add("Custard powder");
            listBox.Items.Add("Cuttlefish");
            listBox.Items.Add("Dab");
            listBox.Items.Add("Daikon");
            listBox.Items.Add("Damsons");
            listBox.Items.Add("Dandelion");
            listBox.Items.Add("Danish blue");
            listBox.Items.Add("Dark chocolate");
            listBox.Items.Add("Date");
            listBox.Items.Add("Demerara sugar");
            listBox.Items.Add("Demi-glace sauce");
            listBox.Items.Add("Desiccated coconut");
            listBox.Items.Add("Desiree");
            listBox.Items.Add("Digestive biscuit");
            listBox.Items.Add("Dijon mustard");
            listBox.Items.Add("Dill");
            listBox.Items.Add("Dim sum wrappers");
            listBox.Items.Add("Dolcelatte");
            listBox.Items.Add("Double cream");
            listBox.Items.Add("Double Gloucester");
            listBox.Items.Add("Dover sole");
            listBox.Items.Add("Dragon fruit");
            listBox.Items.Add("Dried apricots");
            listBox.Items.Add("Dried cherries");
            listBox.Items.Add("Dried chilli");
            listBox.Items.Add("Dried fruit");
            listBox.Items.Add("Dried mixed fruit");
            listBox.Items.Add("Dry sherry");
            listBox.Items.Add("Duck");
            listBox.Items.Add("Duck confit");
            listBox.Items.Add("Duck fat");
            listBox.Items.Add("Dulce de leche");
            listBox.Items.Add("Dumplings");
            listBox.Items.Add("Edam");
            listBox.Items.Add("Eel");
            listBox.Items.Add("Egg");
            listBox.Items.Add("Egg liqueur");
            listBox.Items.Add("Egg wash");
            listBox.Items.Add("Egg white");
            listBox.Items.Add("Egg yolk");
            listBox.Items.Add("Elderberries");
            listBox.Items.Add("Elderflower");
            listBox.Items.Add("Emmental");
            listBox.Items.Add("English muffin");
            listBox.Items.Add("English mustard");
            listBox.Items.Add("Escalope");
            listBox.Items.Add("Evaporated milk");
            listBox.Items.Add("Exotic fruit");
            listBox.Items.Add("Farfalle");
            listBox.Items.Add("Fat");
            listBox.Items.Add("Fennel");
            listBox.Items.Add("Fennel seeds");
            listBox.Items.Add("Fenugreek");
            listBox.Items.Add("Feta");
            listBox.Items.Add("Fettuccine");
            listBox.Items.Add("Field mushroom");
            listBox.Items.Add("Fig");
            listBox.Items.Add("Fillet of beef");
            listBox.Items.Add("Filo pastry");
            listBox.Items.Add("Fish");
            listBox.Items.Add("Fish roe");
            listBox.Items.Add("Fish sauce");
            listBox.Items.Add("Five-spice powder");
            listBox.Items.Add("Flageolet beans");
            listBox.Items.Add("Flaked almonds");
            listBox.Items.Add("Flank");
            listBox.Items.Add("Flapjacks");
            listBox.Items.Add("Flatbread");
            listBox.Items.Add("Flatfish");
            listBox.Items.Add("Fleur de sel");
            listBox.Items.Add("Flour");
            listBox.Items.Add("Flour tortilla");
            listBox.Items.Add("Floury potato");
            listBox.Items.Add("Flying fish");
            listBox.Items.Add("Focaccia");
            listBox.Items.Add("Foie gras");
            listBox.Items.Add("Fondant icing");
            listBox.Items.Add("Fondant potatoes");
            listBox.Items.Add("Fontina cheese");
            listBox.Items.Add("Food colouring");
            listBox.Items.Add("Forced rhubarb");
            listBox.Items.Add("Fortified wine");
            listBox.Items.Add("Fragrant rice");
            listBox.Items.Add("Frangipane");
            listBox.Items.Add("Frankfurter");
            listBox.Items.Add("French beans");
            listBox.Items.Add("French bread");
            listBox.Items.Add("French dressing");
            listBox.Items.Add("Fresh coriander");
            listBox.Items.Add("Fresh tuna");
            listBox.Items.Add("Fromage frais");
            listBox.Items.Add("Fruit");
            listBox.Items.Add("Fruit brandy");
            listBox.Items.Add("Fruit cake");
            listBox.Items.Add("Fruit juice");
            listBox.Items.Add("Fruit salad");
            listBox.Items.Add("Fudge");
            listBox.Items.Add("Fusilli");
            listBox.Items.Add("Galangal");
            listBox.Items.Add("Game");
            listBox.Items.Add("Gammon");
            listBox.Items.Add("Garam masala");
            listBox.Items.Add("Garlic");
            listBox.Items.Add("Garlic and herb cream cheese");
            listBox.Items.Add("Garlic bread");
            listBox.Items.Add("Gelatine");
            listBox.Items.Add("Ghee");
            listBox.Items.Add("Gherkin");
            listBox.Items.Add("Giblets");
            listBox.Items.Add("Gin");
            listBox.Items.Add("Ginger");
            listBox.Items.Add("Ginger ale");
            listBox.Items.Add("Ginger beer");
            listBox.Items.Add("Ginger biscuit");
            listBox.Items.Add("Gingerbread");
            listBox.Items.Add("Glace cherries");
            listBox.Items.Add("Globe artichoke");
            listBox.Items.Add("Glucose");
            listBox.Items.Add("Gnocchi");
            listBox.Items.Add("Goats' cheese");
            listBox.Items.Add("Goats' milk");
            listBox.Items.Add("Golden syrup");
            listBox.Items.Add("Goose");
            listBox.Items.Add("Goose fat");
            listBox.Items.Add("Gooseberry");
            listBox.Items.Add("Gorgonzola");
            listBox.Items.Add("Gouda");
            listBox.Items.Add("Grain");
            listBox.Items.Add("Grape juice");
            listBox.Items.Add("Grapefruit");
            listBox.Items.Add("Grapefruit juice");
            listBox.Items.Add("Grapes");
            listBox.Items.Add("Grapeseed oil");
            listBox.Items.Add("Gratin");
            listBox.Items.Add("Gravy");
            listBox.Items.Add("Gravy browning");
            listBox.Items.Add("Green banana");
            listBox.Items.Add("Green beans");
            listBox.Items.Add("Green cabbage");
            listBox.Items.Add("Green lentil");
            listBox.Items.Add("Green tea");
            listBox.Items.Add("Greengages");
            listBox.Items.Add("Grey mullet");
            listBox.Items.Add("Ground almonds");
            listBox.Items.Add("Ground ginger");
            listBox.Items.Add("Grouse");
            listBox.Items.Add("Gruyère");
            listBox.Items.Add("Guacamole");
            listBox.Items.Add("Guava");
            listBox.Items.Add("Guinea fowl");
            listBox.Items.Add("Gurnard");
            listBox.Items.Add("Habañero chillies");
            listBox.Items.Add("Haddock");
            listBox.Items.Add("Haggis");
            listBox.Items.Add("Hake");
            listBox.Items.Add("Halibut");
            listBox.Items.Add("Halloumi cheese");
            listBox.Items.Add("Ham");
            listBox.Items.Add("Hare");
            listBox.Items.Add("Haricot beans");
            listBox.Items.Add("Harissa");
            listBox.Items.Add("Hazelnut");
            listBox.Items.Add("Hazelnut oil");
            listBox.Items.Add("Heart");
            listBox.Items.Add("Herbal liqueur");
            listBox.Items.Add("Herbal tea");
            listBox.Items.Add("Herbes de provence");
            listBox.Items.Add("Herbs");
            listBox.Items.Add("Herring");
            listBox.Items.Add("Hogget");
            listBox.Items.Add("Hoisin sauce");
            listBox.Items.Add("Hoki");
            listBox.Items.Add("Hollandaise sauce");
            listBox.Items.Add("Hominy");
            listBox.Items.Add("Honey");
            listBox.Items.Add("Honeycomb");
            listBox.Items.Add("Horseradish");
            listBox.Items.Add("Horseradish sauce");
            listBox.Items.Add("Hot cross buns");
            listBox.Items.Add("Hummus");
            listBox.Items.Add("Hunza apricots");
            listBox.Items.Add("Ice cream");
            listBox.Items.Add("Iceberg lettuce");
            listBox.Items.Add("Icing");
            listBox.Items.Add("Icing sugar");
            listBox.Items.Add("Irish stout");
            listBox.Items.Add("Jaggery");
            listBox.Items.Add("Jam");
            listBox.Items.Add("January King cabbage");
            listBox.Items.Add("Japanese pumpkin");
            listBox.Items.Add("Jelly");
            listBox.Items.Add("Jerk seasoning");
            listBox.Items.Add("Jersey Royal potatoes");
            listBox.Items.Add("Jerusalem artichoke");
            listBox.Items.Add("John Dory");
            listBox.Items.Add("Jujube");
            listBox.Items.Add("Juniper berries");
            listBox.Items.Add("Jus");
            listBox.Items.Add("Kabana");
            listBox.Items.Add("Kale");
            listBox.Items.Add("Ketchup");
            listBox.Items.Add("Ketjap manis");
            listBox.Items.Add("Kidney");
            listBox.Items.Add("Kidney beans");
            listBox.Items.Add("King Edward");
            listBox.Items.Add("Kipper");
            listBox.Items.Add("Kirsch");
            listBox.Items.Add("Kiwi fruit");
            listBox.Items.Add("Kohlrabi");
            listBox.Items.Add("Kumquat");
            listBox.Items.Add("Lager");
            listBox.Items.Add("Lamb");
            listBox.Items.Add("Lamb breast");
            listBox.Items.Add("Lamb chop");
            listBox.Items.Add("Lamb fillet");
            listBox.Items.Add("Lamb kidney");
            listBox.Items.Add("Lamb loin");
            listBox.Items.Add("Lamb mince");
            listBox.Items.Add("Lamb neck");
            listBox.Items.Add("Lamb rump");
            listBox.Items.Add("Lamb shank");
            listBox.Items.Add("Lamb shoulder");
            listBox.Items.Add("Lamb stock");
            listBox.Items.Add("Lancashire");
            listBox.Items.Add("Langoustine");
            listBox.Items.Add("Lard");
            listBox.Items.Add("Lardons");
            listBox.Items.Add("Lasagne");
            listBox.Items.Add("Lasagne sheets");
            listBox.Items.Add("Laverbread");
            listBox.Items.Add("Leek");
            listBox.Items.Add("Leg of lamb");
            listBox.Items.Add("Lemon");
            listBox.Items.Add("Lemon balm");
            listBox.Items.Add("Lemon curd");
            listBox.Items.Add("Lemon juice");
            listBox.Items.Add("Lemon sole");
            listBox.Items.Add("Lemonade");
            listBox.Items.Add("Lemongrass");
            listBox.Items.Add("Lentils");
            listBox.Items.Add("Lettuce");
            listBox.Items.Add("Lime");
            listBox.Items.Add("Lime cordial");
            listBox.Items.Add("Lime juice");
            listBox.Items.Add("Lime leaves");
            listBox.Items.Add("Lime pickle");
            listBox.Items.Add("Ling");
            listBox.Items.Add("Lingonberry");
            listBox.Items.Add("Linguine");
            listBox.Items.Add("Liqueur");
            listBox.Items.Add("Liquorice");
            listBox.Items.Add("Little Gem lettuce");
            listBox.Items.Add("Liver");
            listBox.Items.Add("Loaf cake");
            listBox.Items.Add("Lobster");
            listBox.Items.Add("Loganberry");
            listBox.Items.Add("Long-grain rice");
            listBox.Items.Add("Lovage");
            listBox.Items.Add("Lychee");
            listBox.Items.Add("Macadamia");
            listBox.Items.Add("Macaroni");
            listBox.Items.Add("Macaroon");
            listBox.Items.Add("Mace");
            listBox.Items.Add("Mackerel");
            listBox.Items.Add("Madeira");
            listBox.Items.Add("Madeira cake");
            listBox.Items.Add("Madeleines");
            listBox.Items.Add("Maize");
            listBox.Items.Add("Malted grain bread");
            listBox.Items.Add("Manchego");
            listBox.Items.Add("Mandarin");
            listBox.Items.Add("Mangetout");
            listBox.Items.Add("Mango");
            listBox.Items.Add("Mango chutney");
            listBox.Items.Add("Mango juice");
            listBox.Items.Add("Mango pickle");
            listBox.Items.Add("Mangosteen");
            listBox.Items.Add("Maple syrup");
            listBox.Items.Add("Margarine");
            listBox.Items.Add("Marjoram");
            listBox.Items.Add("Marmalade");
            listBox.Items.Add("Marrow");
            listBox.Items.Add("Marrowfat peas");
            listBox.Items.Add("Marsala wine");
            listBox.Items.Add("Marshmallow");
            listBox.Items.Add("Marzipan");
            listBox.Items.Add("Mascarpone");
            listBox.Items.Add("Mashed potato");
            listBox.Items.Add("Matzo");
            listBox.Items.Add("Mayonnaise");
            listBox.Items.Add("Medlars");
            listBox.Items.Add("Megrim");
            listBox.Items.Add("Melon");
            listBox.Items.Add("Melon seeds");
            listBox.Items.Add("Meringue");
            listBox.Items.Add("Mesclun");
            listBox.Items.Add("Milk");
            listBox.Items.Add("Milk chocolate");
            listBox.Items.Add("Milkshake");
            listBox.Items.Add("Millet");
            listBox.Items.Add("Millet flour");
            listBox.Items.Add("Mince");
            listBox.Items.Add("Mince pies");
            listBox.Items.Add("Mincemeat");
            listBox.Items.Add("Mint");
            listBox.Items.Add("Mint sauce");
            listBox.Items.Add("Mirepoix");
            listBox.Items.Add("Mirin");
            listBox.Items.Add("Miso");
            listBox.Items.Add("Mixed berries");
            listBox.Items.Add("Mixed dried beans");
            listBox.Items.Add("Mixed fish");
            listBox.Items.Add("Mixed nuts");
            listBox.Items.Add("Mixed spice");
            listBox.Items.Add("Mixed spices");
            listBox.Items.Add("Molasses");
            listBox.Items.Add("Monk's beard");
            listBox.Items.Add("Monkfish");
            listBox.Items.Add("Morel");
            listBox.Items.Add("Mortadella");
            listBox.Items.Add("Mozzarella");
            listBox.Items.Add("Muesli");
            listBox.Items.Add("Muffins");
            listBox.Items.Add("Mulberries");
            listBox.Items.Add("Mulled wine");
            listBox.Items.Add("Mung beans");
            listBox.Items.Add("Mushroom");
            listBox.Items.Add("Mussels");
            listBox.Items.Add("Mustard");
            listBox.Items.Add("Mustard cress");
            listBox.Items.Add("Mustard leaves");
            listBox.Items.Add("Mustard oil");
            listBox.Items.Add("Mustard powder");
            listBox.Items.Add("Mustard seeds");
            listBox.Items.Add("Mutton");
            listBox.Items.Add("Naan bread");
            listBox.Items.Add("Nachos");
            listBox.Items.Add("Nashi");
            listBox.Items.Add("Nasturtium");
            listBox.Items.Add("Nectarine");
            listBox.Items.Add("Nettle");
            listBox.Items.Add("New potatoes");
            listBox.Items.Add("Nibbed almonds");
            listBox.Items.Add("Noodle soup");
            listBox.Items.Add("Noodles");
            listBox.Items.Add("Nori");
            listBox.Items.Add("Nougat");
            listBox.Items.Add("Nut");
            listBox.Items.Add("Nutmeg");
            listBox.Items.Add("Oatcakes");
            listBox.Items.Add("Oatmeal");
            listBox.Items.Add("Oats");
            listBox.Items.Add("Octopus");
            listBox.Items.Add("Offal");
            listBox.Items.Add("Oil");
            listBox.Items.Add("Oily fish");
            listBox.Items.Add("Okra");
            listBox.Items.Add("Olive");
            listBox.Items.Add("Olive oil");
            listBox.Items.Add("Onion");
            listBox.Items.Add("Orange");
            listBox.Items.Add("Orange juice");
            listBox.Items.Add("Orange liqueur");
            listBox.Items.Add("Oregano");
            listBox.Items.Add("Ouzo");
            listBox.Items.Add("Oxtail");
            listBox.Items.Add("Oyster");
            listBox.Items.Add("Oyster mushrooms");
            listBox.Items.Add("Oyster sauce");
            listBox.Items.Add("Paella");
            listBox.Items.Add("Pak choi");
            listBox.Items.Add("Palm sugar");
            listBox.Items.Add("Pancakes");
            listBox.Items.Add("Pancetta");
            listBox.Items.Add("Pandan leaves");
            listBox.Items.Add("Paneer");
            listBox.Items.Add("Panettone");
            listBox.Items.Add("Papaya");
            listBox.Items.Add("Pappardelle");
            listBox.Items.Add("Paprika");
            listBox.Items.Add("Parfait");
            listBox.Items.Add("Parmesan");
            listBox.Items.Add("Parsley");
            listBox.Items.Add("Parsnip");
            listBox.Items.Add("Partridge");
            listBox.Items.Add("Passata");
            listBox.Items.Add("Passion fruit");
            listBox.Items.Add("Passion fruit juice");
            listBox.Items.Add("Pasta");
            listBox.Items.Add("Pastrami");
            listBox.Items.Add("Pastry");
            listBox.Items.Add("Pasty");
            listBox.Items.Add("Pâte");
            listBox.Items.Add("Paw-paw");
            listBox.Items.Add("Pea shoots");
            listBox.Items.Add("Peach");
            listBox.Items.Add("Peanut butter");
            listBox.Items.Add("Peanut oil");
            listBox.Items.Add("Peanuts");
            listBox.Items.Add("Pear");
            listBox.Items.Add("Pearl barley");
            listBox.Items.Add("Peas");
            listBox.Items.Add("Pecan");
            listBox.Items.Add("Pecorino");
            listBox.Items.Add("Pectin");
            listBox.Items.Add("Peel");
            listBox.Items.Add("Penne");
            listBox.Items.Add("Pepper");
            listBox.Items.Add("Peppercorn");
            listBox.Items.Add("Pepperoni");
            listBox.Items.Add("Perch");
            listBox.Items.Add("Perry");
            listBox.Items.Add("Pesto");
            listBox.Items.Add("Pheasant");
            listBox.Items.Add("Piccalilli");
            listBox.Items.Add("Pickle");
            listBox.Items.Add("Pickled onion");
            listBox.Items.Add("Pie");
            listBox.Items.Add("Pig cheeks");
            listBox.Items.Add("Pigeon");
            listBox.Items.Add("Pigeon peas");
            listBox.Items.Add("Pike");
            listBox.Items.Add("Pine nut");
            listBox.Items.Add("Pineapple");
            listBox.Items.Add("Pineapple juice");
            listBox.Items.Add("Pink Fir Apple");
            listBox.Items.Add("Pink peppercorn");
            listBox.Items.Add("Pinto beans");
            listBox.Items.Add("Piri-piri");
            listBox.Items.Add("Pistachio");
            listBox.Items.Add("Pitta bread");
            listBox.Items.Add("Pizza");
            listBox.Items.Add("Plaice");
            listBox.Items.Add("Plain flour");
            listBox.Items.Add("Plantain");
            listBox.Items.Add("Plum");
            listBox.Items.Add("Polenta");
            listBox.Items.Add("Pollack");
            listBox.Items.Add("Pollock");
            listBox.Items.Add("Pomegranate");
            listBox.Items.Add("Pomegranate juice");
            listBox.Items.Add("Pomelo");
            listBox.Items.Add("Popcorn");
            listBox.Items.Add("Poppy seeds");
            listBox.Items.Add("Porcini");
            listBox.Items.Add("Pork");
            listBox.Items.Add("Pork belly");
            listBox.Items.Add("Pork chop");
            listBox.Items.Add("Pork fillet");
            listBox.Items.Add("Pork leg");
            listBox.Items.Add("Pork loin");
            listBox.Items.Add("Pork mince");
            listBox.Items.Add("Pork sausages");
            listBox.Items.Add("Pork shoulder");
            listBox.Items.Add("Pork spare rib");
            listBox.Items.Add("Port");
            listBox.Items.Add("Portobello mushrooms");
            listBox.Items.Add("Potato");
            listBox.Items.Add("Potato rösti");
            listBox.Items.Add("Potato wedges");
            listBox.Items.Add("Poultry");
            listBox.Items.Add("Poussin");
            listBox.Items.Add("Praline");
            listBox.Items.Add("Prawn");
            listBox.Items.Add("Prawn crackers");
            listBox.Items.Add("Preserved lemons");
            listBox.Items.Add("Preserves");
            listBox.Items.Add("Prosciutto");
            listBox.Items.Add("Prune");
            listBox.Items.Add("Prune juice");
            listBox.Items.Add("Pudding rice");
            listBox.Items.Add("Puff pastry");
            listBox.Items.Add("Pulled pork");
            listBox.Items.Add("Pumpernickel bread");
            listBox.Items.Add("Pumpkin");
            listBox.Items.Add("Pumpkin seed");
            listBox.Items.Add("Purple sprouting broccoli");
            listBox.Items.Add("Puy lentils");
            listBox.Items.Add("Quail");
            listBox.Items.Add("Quail's egg");
            listBox.Items.Add("Quark");
            listBox.Items.Add("Quatre-epices");
            listBox.Items.Add("Quince");
            listBox.Items.Add("Quinoa");
            listBox.Items.Add("Rabbit");
            listBox.Items.Add("Rack of lamb");
            listBox.Items.Add("Radicchio");
            listBox.Items.Add("Radish");
            listBox.Items.Add("Rainbow chard");
            listBox.Items.Add("Rainbow trout");
            listBox.Items.Add("Raisins");
            listBox.Items.Add("Raita");
            listBox.Items.Add("Rapeseed oil");
            listBox.Items.Add("Ras-el-hanout");
            listBox.Items.Add("Raspberry");
            listBox.Items.Add("Raspberry jam");
            listBox.Items.Add("Ratafia biscuits");
            listBox.Items.Add("Ratatouille");
            listBox.Items.Add("Red cabbage");
            listBox.Items.Add("Red Leicester");
            listBox.Items.Add("Red lentil");
            listBox.Items.Add("Red mullet");
            listBox.Items.Add("Red onion");
            listBox.Items.Add("Red rice");
            listBox.Items.Add("Red snapper");
            listBox.Items.Add("Red wine");
            listBox.Items.Add("Red wine vinegar");
            listBox.Items.Add("Redcurrant");
            listBox.Items.Add("Redcurrant jelly");
            listBox.Items.Add("Rennet");
            listBox.Items.Add("Rhubarb");
            listBox.Items.Add("Rib of beef");
            listBox.Items.Add("Rice");
            listBox.Items.Add("Rice flour");
            listBox.Items.Add("Rice noodles");
            listBox.Items.Add("Rice pudding");
            listBox.Items.Add("Rice vinegar");
            listBox.Items.Add("Rice wine");
            listBox.Items.Add("Ricotta");
            listBox.Items.Add("Rigatoni");
            listBox.Items.Add("Risotto");
            listBox.Items.Add("Risotto rice");
            listBox.Items.Add("Roast beef");
            listBox.Items.Add("Roast chicken");
            listBox.Items.Add("Roast lamb");
            listBox.Items.Add("Roast pork");
            listBox.Items.Add("Roast potatoes");
            listBox.Items.Add("Roast turkey");
            listBox.Items.Add("Roasted vegetables");
            listBox.Items.Add("Rock salmon");
            listBox.Items.Add("Rock salt");
            listBox.Items.Add("Rocket");
            listBox.Items.Add("Root beer");
            listBox.Items.Add("Root vegetable");
            listBox.Items.Add("Roquefort");
            listBox.Items.Add("Rose wine");
            listBox.Items.Add("Rosehip syrup");
            listBox.Items.Add("Rosemary");
            listBox.Items.Add("Rosewater");
            listBox.Items.Add("Rouille");
            listBox.Items.Add("Royal icing");
            listBox.Items.Add("Rum");
            listBox.Items.Add("Rump");
            listBox.Items.Add("Runner beans");
            listBox.Items.Add("Rye bread");
            listBox.Items.Add("Rye flour");
            listBox.Items.Add("Safflower oil");
            listBox.Items.Add("Saffron");
            listBox.Items.Add("Sage");
            listBox.Items.Add("Salad");
            listBox.Items.Add("Salad cream");
            listBox.Items.Add("Salad leaves");
            listBox.Items.Add("Salami");
            listBox.Items.Add("Salmon");
            listBox.Items.Add("Salsa");
            listBox.Items.Add("Salsify");
            listBox.Items.Add("Salt");
            listBox.Items.Add("Salt beef");
            listBox.Items.Add("Salt cod");
            listBox.Items.Add("Sambuca");
            listBox.Items.Add("Samphire");
            listBox.Items.Add("Sardine");
            listBox.Items.Add("Satsuma");
            listBox.Items.Add("Sauces");
            listBox.Items.Add("Saucisson");
            listBox.Items.Add("Sausage");
            listBox.Items.Add("Savory");
            listBox.Items.Add("Savoy cabbage");
            listBox.Items.Add("Scallop");
            listBox.Items.Add("Scotch bonnet chilli");
            listBox.Items.Add("Scrag");
            listBox.Items.Add("Sea bass");
            listBox.Items.Add("Sea bream");
            listBox.Items.Add("Sea salt");
            listBox.Items.Add("Sea trout");
            listBox.Items.Add("Seafood");
            listBox.Items.Add("Seasoning");
            listBox.Items.Add("Seaweed");
            listBox.Items.Add("Seeds");
            listBox.Items.Add("Self-raising flour");
            listBox.Items.Add("Semolina");
            listBox.Items.Add("Serrano ham");
            listBox.Items.Add("Sesame oil");
            listBox.Items.Add("Sesame seeds");
            listBox.Items.Add("Seville orange");
            listBox.Items.Add("Shallot");
            listBox.Items.Add("Sharon fruit");
            listBox.Items.Add("Shellfish");
            listBox.Items.Add("Sherry");
            listBox.Items.Add("Sherry vinegar");
            listBox.Items.Add("Shiitake mushroom");
            listBox.Items.Add("Shin");
            listBox.Items.Add("Shortbread");
            listBox.Items.Add("Shortcrust pastry");
            listBox.Items.Add("Sichuan pepper");
            listBox.Items.Add("Silverside");
            listBox.Items.Add("Single cream");
            listBox.Items.Add("Sirloin");
            listBox.Items.Add("Skate");
            listBox.Items.Add("Sloe");
            listBox.Items.Add("Sloe gin");
            listBox.Items.Add("Smoked cheese");
            listBox.Items.Add("Smoked fish");
            listBox.Items.Add("Smoked haddock");
            listBox.Items.Add("Smoked mackerel");
            listBox.Items.Add("Smoked salmon");
            listBox.Items.Add("Smoked trout");
            listBox.Items.Add("Snapper");
            listBox.Items.Add("Soba noodles");
            listBox.Items.Add("Soda");
            listBox.Items.Add("Soda bread");
            listBox.Items.Add("Sole");
            listBox.Items.Add("Sorbet");
            listBox.Items.Add("Sorrel");
            listBox.Items.Add("Soup");
            listBox.Items.Add("Sourdough bread");
            listBox.Items.Add("Soured cream");
            listBox.Items.Add("Soy sauce");
            listBox.Items.Add("Soya beans");
            listBox.Items.Add("Soya flour");
            listBox.Items.Add("Soya milk");
            listBox.Items.Add("Soya oil");
            listBox.Items.Add("Spaghetti");
            listBox.Items.Add("Spaghetti squash");
            listBox.Items.Add("Sparkling wine");
            listBox.Items.Add("Spelt");
            listBox.Items.Add("Spelt flour");
            listBox.Items.Add("Spices");
            listBox.Items.Add("Spinach");
            listBox.Items.Add("Split peas");
            listBox.Items.Add("Sponge cake");
            listBox.Items.Add("Spring greens");
            listBox.Items.Add("Spring onion");
            listBox.Items.Add("Spring roll wrappers");
            listBox.Items.Add("Squash");
            listBox.Items.Add("Squid");
            listBox.Items.Add("Star anise");
            listBox.Items.Add("Starfruit");
            listBox.Items.Add("Steak");
            listBox.Items.Add("Stem ginger");
            listBox.Items.Add("Stew");
            listBox.Items.Add("Stewing lamb");
            listBox.Items.Add("Stilton");
            listBox.Items.Add("Stock");
            listBox.Items.Add("Straw mushroom");
            listBox.Items.Add("Strawberry");
            listBox.Items.Add("Strawberry jam");
            listBox.Items.Add("Strega liqueur");
            listBox.Items.Add("String beans");
            listBox.Items.Add("Strong white flour");
            listBox.Items.Add("Stuffing");
            listBox.Items.Add("Sucralose");
            listBox.Items.Add("Suet");
            listBox.Items.Add("Sugar");
            listBox.Items.Add("Sugar-snap peas");
            listBox.Items.Add("Sultanas");
            listBox.Items.Add("Sumac");
            listBox.Items.Add("Summer cabbage");
            listBox.Items.Add("Summer fruit");
            listBox.Items.Add("Sunflower oil");
            listBox.Items.Add("Sunflower seed");
            listBox.Items.Add("Sushi rice");
            listBox.Items.Add("Swede");
            listBox.Items.Add("Sweet potato");
            listBox.Items.Add("Sweet sherry");
            listBox.Items.Add("Sweetbread");
            listBox.Items.Add("Sweetcorn");
            listBox.Items.Add("Swiss chard");
            listBox.Items.Add("Swiss rolls and roulades");
            listBox.Items.Add("Swordfish");
            listBox.Items.Add("Syrup");
            listBox.Items.Add("T-bone steak");
            listBox.Items.Add("Tabasco");
            listBox.Items.Add("Taco");
            listBox.Items.Add("Tagliatelle");
            listBox.Items.Add("Tahini");
            listBox.Items.Add("Taleggio");
            listBox.Items.Add("Tamari");
            listBox.Items.Add("Tamarillo");
            listBox.Items.Add("Tamarind");
            listBox.Items.Add("Tangerine");
            listBox.Items.Add("Tapenade");
            listBox.Items.Add("Tapioca");
            listBox.Items.Add("Taro");
            listBox.Items.Add("Tarragon");
            listBox.Items.Add("Tartare sauce");
            listBox.Items.Add("Tayberry");
            listBox.Items.Add("Tea");
            listBox.Items.Add("Tempura");
            listBox.Items.Add("Tequila");
            listBox.Items.Add("Teriyaki");
            listBox.Items.Add("Teriyaki sauce");
            listBox.Items.Add("Terrine");
            listBox.Items.Add("Thai basil");
            listBox.Items.Add("Thyme");
            listBox.Items.Add("Tilapia");
            listBox.Items.Add("Tinned tuna");
            listBox.Items.Add("Toffee");
            listBox.Items.Add("Tofu");
            listBox.Items.Add("Tomato");
            listBox.Items.Add("Tomato chutney");
            listBox.Items.Add("Tomato juice");
            listBox.Items.Add("Tomato puree");
            listBox.Items.Add("Tongue");
            listBox.Items.Add("Tonic");
            listBox.Items.Add("Topside");
            listBox.Items.Add("Tortellini");
            listBox.Items.Add("Tripe");
            listBox.Items.Add("Trout");
            listBox.Items.Add("Truffle");
            listBox.Items.Add("Truffle oil");
            listBox.Items.Add("Turbot");
            listBox.Items.Add("Turkey");
            listBox.Items.Add("Turkey breast");
            listBox.Items.Add("Turkey mince");
            listBox.Items.Add("Turkish delight");
            listBox.Items.Add("Turmeric");
            listBox.Items.Add("Turnip");
            listBox.Items.Add("Unleavened bread");
            listBox.Items.Add("Vacherin");
            listBox.Items.Add("Vanilla essence");
            listBox.Items.Add("Vanilla extract");
            listBox.Items.Add("Vanilla pod");
            listBox.Items.Add("Veal");
            listBox.Items.Add("Vegetable oil");
            listBox.Items.Add("Vegetable shortening");
            listBox.Items.Add("Vegetable stock");
            listBox.Items.Add("Vegetables");
            listBox.Items.Add("Vegetarian sausage");
            listBox.Items.Add("Venison");
            listBox.Items.Add("Verjus");
            listBox.Items.Add("Vermicelli");
            listBox.Items.Add("Vermouth");
            listBox.Items.Add("Vine leaves");
            listBox.Items.Add("Vinegar");
            listBox.Items.Add("Vodka");
            listBox.Items.Add("Vodka cocktail");
            listBox.Items.Add("Waffles");
            listBox.Items.Add("Walnut");
            listBox.Items.Add("Walnut oil");
            listBox.Items.Add("Wasabi");
            listBox.Items.Add("Water chestnut");
            listBox.Items.Add("Watercress");
            listBox.Items.Add("Watermelon");
            listBox.Items.Add("Waxy potato");
            listBox.Items.Add("Webbs lettuce");
            listBox.Items.Add("Wensleydale");
            listBox.Items.Add("Wheatgerm");
            listBox.Items.Add("Whelk");
            listBox.Items.Add("Whipping cream");
            listBox.Items.Add("Whisky");
            listBox.Items.Add("Whisky cocktail");
            listBox.Items.Add("Whisky liqueur");
            listBox.Items.Add("White bread");
            listBox.Items.Add("White cabbage");
            listBox.Items.Add("White chocolate");
            listBox.Items.Add("White fish");
            listBox.Items.Add("White pepper");
            listBox.Items.Add("White wine");
            listBox.Items.Add("White wine vinegar");
            listBox.Items.Add("Whitebait");
            listBox.Items.Add("Whitecurrant");
            listBox.Items.Add("Whiting");
            listBox.Items.Add("Wholegrain mustard");
            listBox.Items.Add("Wholemeal bread");
            listBox.Items.Add("Wholemeal flour");
            listBox.Items.Add("Wild duck");
            listBox.Items.Add("Wild garlic");
            listBox.Items.Add("Wild mushrooms");
            listBox.Items.Add("Wild rice");
            listBox.Items.Add("Wine");
            listBox.Items.Add("Winkles");
            listBox.Items.Add("Wood pigeon");
            listBox.Items.Add("Worcestershire sauce");
            listBox.Items.Add("Wraps");
            listBox.Items.Add("Yam");
            listBox.Items.Add("Yeast");
            listBox.Items.Add("Yellow lentil");
            listBox.Items.Add("Yoghurt");
            listBox.Items.Add("Zander");
            listBox.Items.Add("Zest");




            //Get Data From Azure
            //Create new ListBox or List View Element
            //Add Item
            /*var str = Application.GetResourceStream(new Uri("FOOD.txt"), UriKind.Relative);
            StreamReader sReader = new StreamReader(str.Stream);
            listBox.Items.Add(sReader.ReadToEnd());
            int x = 0;
            while (!sReader.EndOfStream)
            {
                x++;
                listBox.Items.Add(x+". "+sReader.ReadLine());
            }
            */
        }

        private void button_Click(object sender, RoutedEventArgs e)
        {
            
            if (listBox.SelectedIndex != -1)
            {

                ArrayList Ingredients = new ArrayList();
                string ingredients="";

                foreach (var item in listBox.SelectedItems)
                {
                    ingredients = ingredients + item.ToString()+";";
                    
                    
                }
                (App.Current as App).NavigateText = ingredients;
                
                Frame.Navigate(typeof(ResultPage),ingredients);
            }
            

        }
        

        private void Search_QueryChanged(SearchBox sender, SearchBoxQueryChangedEventArgs args)
        {
            RealTimeSearch();
        }

        private void Search_QuerySubmitted(SearchBox sender, SearchBoxQuerySubmittedEventArgs args)
        {
            NextSearch();
        }
        private void RealTimeSearch()
        {
            
            //string query = textBox.Text.ToUpper();
            for (int i = 0; i <= listBox.Items.Count - 1; i++)
            {
                if (listBox.Items[i].ToString().ToUpper().Contains(Search.QueryText.ToUpper()))
                {

                    listBox.ScrollIntoView(listBox.Items[i]);
                    //listBox.SelectedItem=(listBox.Items[i]);
                    

                    CurrentSearch = i;
                    break;

                }
            }
            


        }
        private void NextSearch()
        {

            for (int i = CurrentSearch + 1; i <= listBox.Items.Count - 1; i++)
            {
                if (listBox.Items[i].ToString().ToUpper().Contains(Search.QueryText.ToUpper()))
                {

                    listBox.ScrollIntoView(listBox.Items[i]);
                    //listBox.SelectedItem = (listBox.Items[i]);
                    
                    CurrentSearch = i;
                    break;
                }
            }
        }
       
        

        
    }
}
        


    

